#!/usr/bin/env sh
set -eu

output=
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    output=$2
    shift 2
  else
    shift
  fi
done

[ -n "$output" ] || exit 2
printf '%s\n' "${FAKE_CURL_CONTENT:-partial download}" >"$output"
[ "${FAKE_CURL_FAIL:-0}" != "1" ] || exit 22
